// @generated by protobuf-ts 2.11.1 with parameter force_disable_services
// @generated from protobuf file "opentelemetry/proto/collector/metrics/v1/metrics_service.proto" (package "opentelemetry.proto.collector.metrics.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ResourceMetrics } from "../../../metrics/v1/metrics.ts";
/**
 * @generated from protobuf message opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest
 */
export interface ExportMetricsServiceRequest {
  /**
   * @generated from protobuf field: repeated opentelemetry.proto.metrics.v1.ResourceMetrics resource_metrics = 1
   */
  resourceMetrics: ResourceMetrics[];
}
/**
 * @generated from protobuf message opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse
 */
export interface ExportMetricsServiceResponse {
  /**
   * @generated from protobuf field: opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess partial_success = 1
   */
  partialSuccess?: ExportMetricsPartialSuccess;
}
/**
 * @generated from protobuf message opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess
 */
export interface ExportMetricsPartialSuccess {
  /**
   * @generated from protobuf field: int64 rejected_data_points = 1
   */
  rejectedDataPoints: bigint;
  /**
   * @generated from protobuf field: string error_message = 2
   */
  errorMessage: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class ExportMetricsServiceRequest$Type extends MessageType<ExportMetricsServiceRequest> {
  constructor() {
    super("opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest", [
      { no: 1, name: "resource_metrics", kind: "message", repeat: 2, /*RepeatType.UNPACKED*/ T: () => ResourceMetrics },
    ]);
  }
  override create(value?: PartialMessage<ExportMetricsServiceRequest>): ExportMetricsServiceRequest {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.resourceMetrics = [];
    if (value !== undefined) {
      reflectionMergePartial<ExportMetricsServiceRequest>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: ExportMetricsServiceRequest,
  ): ExportMetricsServiceRequest {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* repeated opentelemetry.proto.metrics.v1.ResourceMetrics resource_metrics */ 1:
          message.resourceMetrics.push(ResourceMetrics.internalBinaryRead(reader, reader.uint32(), options));
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(
    message: ExportMetricsServiceRequest,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* repeated opentelemetry.proto.metrics.v1.ResourceMetrics resource_metrics = 1; */
    for (let i = 0; i < message.resourceMetrics.length; i++) {
      ResourceMetrics.internalBinaryWrite(
        message.resourceMetrics[i],
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest
 */
export const ExportMetricsServiceRequest = new ExportMetricsServiceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ExportMetricsServiceResponse$Type extends MessageType<ExportMetricsServiceResponse> {
  constructor() {
    super("opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse", [
      { no: 1, name: "partial_success", kind: "message", T: () => ExportMetricsPartialSuccess },
    ]);
  }
  override create(value?: PartialMessage<ExportMetricsServiceResponse>): ExportMetricsServiceResponse {
    const message = globalThis.Object.create(this.messagePrototype!);
    if (value !== undefined) {
      reflectionMergePartial<ExportMetricsServiceResponse>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: ExportMetricsServiceResponse,
  ): ExportMetricsServiceResponse {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess partial_success */ 1:
          message.partialSuccess = ExportMetricsPartialSuccess.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.partialSuccess,
          );
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(
    message: ExportMetricsServiceResponse,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess partial_success = 1; */
    if (message.partialSuccess) {
      ExportMetricsPartialSuccess.internalBinaryWrite(
        message.partialSuccess,
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse
 */
export const ExportMetricsServiceResponse = new ExportMetricsServiceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ExportMetricsPartialSuccess$Type extends MessageType<ExportMetricsPartialSuccess> {
  constructor() {
    super("opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess", [
      { no: 1, name: "rejected_data_points", kind: "scalar", T: 3, /*ScalarType.INT64*/ L: 0 /*LongType.BIGINT*/ },
      { no: 2, name: "error_message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
  override create(value?: PartialMessage<ExportMetricsPartialSuccess>): ExportMetricsPartialSuccess {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.rejectedDataPoints = 0n;
    message.errorMessage = "";
    if (value !== undefined) {
      reflectionMergePartial<ExportMetricsPartialSuccess>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: ExportMetricsPartialSuccess,
  ): ExportMetricsPartialSuccess {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* int64 rejected_data_points */ 1:
          message.rejectedDataPoints = reader.int64().toBigInt();
          break;
        case /* string error_message */ 2:
          message.errorMessage = reader.string();
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(
    message: ExportMetricsPartialSuccess,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* int64 rejected_data_points = 1; */
    if (message.rejectedDataPoints !== 0n) {
      writer.tag(1, WireType.Varint).int64(message.rejectedDataPoints);
    }
    /* string error_message = 2; */
    if (message.errorMessage !== "") {
      writer.tag(2, WireType.LengthDelimited).string(message.errorMessage);
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess
 */
export const ExportMetricsPartialSuccess = new ExportMetricsPartialSuccess$Type();
