// @generated by protobuf-ts 2.11.1 with parameter force_disable_services
// @generated from protobuf file "opentelemetry/proto/metrics/v1/metrics.proto" (package "opentelemetry.proto.metrics.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { KeyValue } from "../../common/v1/common.ts";
import { InstrumentationScope } from "../../common/v1/common.ts";
import { Resource } from "../../resource/v1/resource.ts";
/**
 * @generated from protobuf message opentelemetry.proto.metrics.v1.ResourceMetrics
 */
export interface ResourceMetrics {
  /**
   * @generated from protobuf field: opentelemetry.proto.resource.v1.Resource resource = 1
   */
  resource?: Resource;
  /**
   * @generated from protobuf field: repeated opentelemetry.proto.metrics.v1.ScopeMetrics scope_metrics = 2
   */
  scopeMetrics: ScopeMetrics[];
  /**
   * @generated from protobuf field: string schema_url = 3
   */
  schemaUrl: string;
}
/**
 * @generated from protobuf message opentelemetry.proto.metrics.v1.ScopeMetrics
 */
export interface ScopeMetrics {
  /**
   * @generated from protobuf field: opentelemetry.proto.common.v1.InstrumentationScope scope = 1
   */
  scope?: InstrumentationScope;
  /**
   * @generated from protobuf field: repeated opentelemetry.proto.metrics.v1.Metric metrics = 2
   */
  metrics: Metric[];
  /**
   * @generated from protobuf field: string schema_url = 3
   */
  schemaUrl: string;
}
/**
 * @generated from protobuf message opentelemetry.proto.metrics.v1.Metric
 */
export interface Metric {
  /**
   * @generated from protobuf field: string name = 1
   */
  name: string;
  /**
   * @generated from protobuf field: string description = 2
   */
  description: string;
  /**
   * @generated from protobuf field: string unit = 3
   */
  unit: string;
  /**
   * @generated from protobuf oneof: data
   */
  data: {
    oneofKind: "gauge";
    /**
     * @generated from protobuf field: opentelemetry.proto.metrics.v1.Gauge gauge = 5
     */
    gauge: Gauge;
  } | {
    oneofKind: "sum";
    /**
     * @generated from protobuf field: opentelemetry.proto.metrics.v1.Sum sum = 7
     */
    sum: Sum;
  } | {
    oneofKind: "histogram";
    /**
     * @generated from protobuf field: opentelemetry.proto.metrics.v1.Histogram histogram = 9
     */
    histogram: Histogram;
  } | {
    oneofKind: "summary";
    /**
     * @generated from protobuf field: opentelemetry.proto.metrics.v1.Summary summary = 11
     */
    summary: Summary;
  } | {
    oneofKind: undefined;
  };
}
/**
 * @generated from protobuf message opentelemetry.proto.metrics.v1.Gauge
 */
export interface Gauge {
  /**
   * @generated from protobuf field: repeated opentelemetry.proto.metrics.v1.NumberDataPoint data_points = 1
   */
  dataPoints: NumberDataPoint[];
}
/**
 * @generated from protobuf message opentelemetry.proto.metrics.v1.Sum
 */
export interface Sum {
  /**
   * @generated from protobuf field: repeated opentelemetry.proto.metrics.v1.NumberDataPoint data_points = 1
   */
  dataPoints: NumberDataPoint[];
  /**
   * @generated from protobuf field: opentelemetry.proto.metrics.v1.AggregationTemporality aggregation_temporality = 2
   */
  aggregationTemporality: AggregationTemporality;
  /**
   * @generated from protobuf field: bool is_monotonic = 3
   */
  isMonotonic: boolean;
}
/**
 * @generated from protobuf message opentelemetry.proto.metrics.v1.Histogram
 */
export interface Histogram {
  /**
   * @generated from protobuf field: repeated opentelemetry.proto.metrics.v1.HistogramDataPoint data_points = 1
   */
  dataPoints: HistogramDataPoint[];
  /**
   * @generated from protobuf field: opentelemetry.proto.metrics.v1.AggregationTemporality aggregation_temporality = 2
   */
  aggregationTemporality: AggregationTemporality;
}
/**
 * @generated from protobuf message opentelemetry.proto.metrics.v1.Summary
 */
export interface Summary {
  /**
   * @generated from protobuf field: repeated opentelemetry.proto.metrics.v1.SummaryDataPoint data_points = 1
   */
  dataPoints: SummaryDataPoint[];
}
/**
 * @generated from protobuf message opentelemetry.proto.metrics.v1.NumberDataPoint
 */
export interface NumberDataPoint {
  /**
   * @generated from protobuf field: repeated opentelemetry.proto.common.v1.KeyValue attributes = 7
   */
  attributes: KeyValue[];
  /**
   * @generated from protobuf field: fixed64 start_time_unix_nano = 2
   */
  startTimeUnixNano: bigint;
  /**
   * @generated from protobuf field: fixed64 time_unix_nano = 3
   */
  timeUnixNano: bigint;
  /**
   * @generated from protobuf oneof: value
   */
  value: {
    oneofKind: "asDouble";
    /**
     * @generated from protobuf field: double as_double = 4
     */
    asDouble: number;
  } | {
    oneofKind: "asInt";
    /**
     * @generated from protobuf field: sfixed64 as_int = 6
     */
    asInt: bigint;
  } | {
    oneofKind: undefined;
  };
}
/**
 * @generated from protobuf message opentelemetry.proto.metrics.v1.HistogramDataPoint
 */
export interface HistogramDataPoint {
  /**
   * @generated from protobuf field: repeated opentelemetry.proto.common.v1.KeyValue attributes = 9
   */
  attributes: KeyValue[];
  /**
   * @generated from protobuf field: fixed64 start_time_unix_nano = 2
   */
  startTimeUnixNano: bigint;
  /**
   * @generated from protobuf field: fixed64 time_unix_nano = 3
   */
  timeUnixNano: bigint;
  /**
   * @generated from protobuf field: uint64 count = 4
   */
  count: bigint;
  /**
   * @generated from protobuf field: double sum = 5
   */
  sum: number;
  /**
   * @generated from protobuf field: repeated uint64 bucket_counts = 6
   */
  bucketCounts: bigint[];
  /**
   * @generated from protobuf field: repeated double explicit_bounds = 7
   */
  explicitBounds: number[];
}
/**
 * @generated from protobuf message opentelemetry.proto.metrics.v1.SummaryDataPoint
 */
export interface SummaryDataPoint {
  /**
   * @generated from protobuf field: repeated opentelemetry.proto.common.v1.KeyValue attributes = 7
   */
  attributes: KeyValue[];
  /**
   * @generated from protobuf field: fixed64 start_time_unix_nano = 2
   */
  startTimeUnixNano: bigint;
  /**
   * @generated from protobuf field: fixed64 time_unix_nano = 3
   */
  timeUnixNano: bigint;
  /**
   * @generated from protobuf field: uint64 count = 4
   */
  count: bigint;
  /**
   * @generated from protobuf field: double sum = 5
   */
  sum: number;
  /**
   * @generated from protobuf field: repeated opentelemetry.proto.metrics.v1.ValueAtQuantile quantile_values = 6
   */
  quantileValues: ValueAtQuantile[];
}
/**
 * @generated from protobuf message opentelemetry.proto.metrics.v1.ValueAtQuantile
 */
export interface ValueAtQuantile {
  /**
   * @generated from protobuf field: double quantile = 1
   */
  quantile: number;
  /**
   * @generated from protobuf field: double value = 2
   */
  value: number;
}
/**
 * @generated from protobuf enum opentelemetry.proto.metrics.v1.AggregationTemporality
 */
export enum AggregationTemporality {
  /**
   * @generated from protobuf enum value: AGGREGATION_TEMPORALITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,
  /**
   * @generated from protobuf enum value: AGGREGATION_TEMPORALITY_DELTA = 1;
   */
  DELTA = 1,
  /**
   * @generated from protobuf enum value: AGGREGATION_TEMPORALITY_CUMULATIVE = 2;
   */
  CUMULATIVE = 2,
}
// @generated message type with reflection information, may provide speed optimized methods
class ResourceMetrics$Type extends MessageType<ResourceMetrics> {
  constructor() {
    super("opentelemetry.proto.metrics.v1.ResourceMetrics", [
      { no: 1, name: "resource", kind: "message", T: () => Resource },
      { no: 2, name: "scope_metrics", kind: "message", repeat: 2, /*RepeatType.UNPACKED*/ T: () => ScopeMetrics },
      { no: 3, name: "schema_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
  override create(value?: PartialMessage<ResourceMetrics>): ResourceMetrics {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.scopeMetrics = [];
    message.schemaUrl = "";
    if (value !== undefined) {
      reflectionMergePartial<ResourceMetrics>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: ResourceMetrics,
  ): ResourceMetrics {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* opentelemetry.proto.resource.v1.Resource resource */ 1:
          message.resource = Resource.internalBinaryRead(reader, reader.uint32(), options, message.resource);
          break;
        case /* repeated opentelemetry.proto.metrics.v1.ScopeMetrics scope_metrics */ 2:
          message.scopeMetrics.push(ScopeMetrics.internalBinaryRead(reader, reader.uint32(), options));
          break;
        case /* string schema_url */ 3:
          message.schemaUrl = reader.string();
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(
    message: ResourceMetrics,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* opentelemetry.proto.resource.v1.Resource resource = 1; */
    if (message.resource) {
      Resource.internalBinaryWrite(message.resource, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
    }
    /* repeated opentelemetry.proto.metrics.v1.ScopeMetrics scope_metrics = 2; */
    for (let i = 0; i < message.scopeMetrics.length; i++) {
      ScopeMetrics.internalBinaryWrite(message.scopeMetrics[i], writer.tag(2, WireType.LengthDelimited).fork(), options)
        .join();
    }
    /* string schema_url = 3; */
    if (message.schemaUrl !== "") {
      writer.tag(3, WireType.LengthDelimited).string(message.schemaUrl);
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.metrics.v1.ResourceMetrics
 */
export const ResourceMetrics = new ResourceMetrics$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScopeMetrics$Type extends MessageType<ScopeMetrics> {
  constructor() {
    super("opentelemetry.proto.metrics.v1.ScopeMetrics", [
      { no: 1, name: "scope", kind: "message", T: () => InstrumentationScope },
      { no: 2, name: "metrics", kind: "message", repeat: 2, /*RepeatType.UNPACKED*/ T: () => Metric },
      { no: 3, name: "schema_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
  override create(value?: PartialMessage<ScopeMetrics>): ScopeMetrics {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.metrics = [];
    message.schemaUrl = "";
    if (value !== undefined) {
      reflectionMergePartial<ScopeMetrics>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: ScopeMetrics,
  ): ScopeMetrics {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* opentelemetry.proto.common.v1.InstrumentationScope scope */ 1:
          message.scope = InstrumentationScope.internalBinaryRead(reader, reader.uint32(), options, message.scope);
          break;
        case /* repeated opentelemetry.proto.metrics.v1.Metric metrics */ 2:
          message.metrics.push(Metric.internalBinaryRead(reader, reader.uint32(), options));
          break;
        case /* string schema_url */ 3:
          message.schemaUrl = reader.string();
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(
    message: ScopeMetrics,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* opentelemetry.proto.common.v1.InstrumentationScope scope = 1; */
    if (message.scope) {
      InstrumentationScope.internalBinaryWrite(message.scope, writer.tag(1, WireType.LengthDelimited).fork(), options)
        .join();
    }
    /* repeated opentelemetry.proto.metrics.v1.Metric metrics = 2; */
    for (let i = 0; i < message.metrics.length; i++) {
      Metric.internalBinaryWrite(message.metrics[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
    }
    /* string schema_url = 3; */
    if (message.schemaUrl !== "") {
      writer.tag(3, WireType.LengthDelimited).string(message.schemaUrl);
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.metrics.v1.ScopeMetrics
 */
export const ScopeMetrics = new ScopeMetrics$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Metric$Type extends MessageType<Metric> {
  constructor() {
    super("opentelemetry.proto.metrics.v1.Metric", [
      { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 3, name: "unit", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 5, name: "gauge", kind: "message", oneof: "data", T: () => Gauge },
      { no: 7, name: "sum", kind: "message", oneof: "data", T: () => Sum },
      { no: 9, name: "histogram", kind: "message", oneof: "data", T: () => Histogram },
      { no: 11, name: "summary", kind: "message", oneof: "data", T: () => Summary },
    ]);
  }
  override create(value?: PartialMessage<Metric>): Metric {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.name = "";
    message.description = "";
    message.unit = "";
    message.data = { oneofKind: undefined };
    if (value !== undefined) {
      reflectionMergePartial<Metric>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: Metric,
  ): Metric {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* string name */ 1:
          message.name = reader.string();
          break;
        case /* string description */ 2:
          message.description = reader.string();
          break;
        case /* string unit */ 3:
          message.unit = reader.string();
          break;
        case /* opentelemetry.proto.metrics.v1.Gauge gauge */ 5:
          message.data = {
            oneofKind: "gauge",
            gauge: Gauge.internalBinaryRead(reader, reader.uint32(), options, (message.data as any).gauge),
          };
          break;
        case /* opentelemetry.proto.metrics.v1.Sum sum */ 7:
          message.data = {
            oneofKind: "sum",
            sum: Sum.internalBinaryRead(reader, reader.uint32(), options, (message.data as any).sum),
          };
          break;
        case /* opentelemetry.proto.metrics.v1.Histogram histogram */ 9:
          message.data = {
            oneofKind: "histogram",
            histogram: Histogram.internalBinaryRead(reader, reader.uint32(), options, (message.data as any).histogram),
          };
          break;
        case /* opentelemetry.proto.metrics.v1.Summary summary */ 11:
          message.data = {
            oneofKind: "summary",
            summary: Summary.internalBinaryRead(reader, reader.uint32(), options, (message.data as any).summary),
          };
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(message: Metric, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
    /* string name = 1; */
    if (message.name !== "") {
      writer.tag(1, WireType.LengthDelimited).string(message.name);
    }
    /* string description = 2; */
    if (message.description !== "") {
      writer.tag(2, WireType.LengthDelimited).string(message.description);
    }
    /* string unit = 3; */
    if (message.unit !== "") {
      writer.tag(3, WireType.LengthDelimited).string(message.unit);
    }
    /* opentelemetry.proto.metrics.v1.Gauge gauge = 5; */
    if (message.data.oneofKind === "gauge") {
      Gauge.internalBinaryWrite(message.data.gauge, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
    }
    /* opentelemetry.proto.metrics.v1.Sum sum = 7; */
    if (message.data.oneofKind === "sum") {
      Sum.internalBinaryWrite(message.data.sum, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
    }
    /* opentelemetry.proto.metrics.v1.Histogram histogram = 9; */
    if (message.data.oneofKind === "histogram") {
      Histogram.internalBinaryWrite(message.data.histogram, writer.tag(9, WireType.LengthDelimited).fork(), options)
        .join();
    }
    /* opentelemetry.proto.metrics.v1.Summary summary = 11; */
    if (message.data.oneofKind === "summary") {
      Summary.internalBinaryWrite(message.data.summary, writer.tag(11, WireType.LengthDelimited).fork(), options)
        .join();
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.metrics.v1.Metric
 */
export const Metric = new Metric$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Gauge$Type extends MessageType<Gauge> {
  constructor() {
    super("opentelemetry.proto.metrics.v1.Gauge", [
      { no: 1, name: "data_points", kind: "message", repeat: 2, /*RepeatType.UNPACKED*/ T: () => NumberDataPoint },
    ]);
  }
  override create(value?: PartialMessage<Gauge>): Gauge {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.dataPoints = [];
    if (value !== undefined) {
      reflectionMergePartial<Gauge>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: Gauge,
  ): Gauge {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* repeated opentelemetry.proto.metrics.v1.NumberDataPoint data_points */ 1:
          message.dataPoints.push(NumberDataPoint.internalBinaryRead(reader, reader.uint32(), options));
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(message: Gauge, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
    /* repeated opentelemetry.proto.metrics.v1.NumberDataPoint data_points = 1; */
    for (let i = 0; i < message.dataPoints.length; i++) {
      NumberDataPoint.internalBinaryWrite(
        message.dataPoints[i],
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.metrics.v1.Gauge
 */
export const Gauge = new Gauge$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Sum$Type extends MessageType<Sum> {
  constructor() {
    super("opentelemetry.proto.metrics.v1.Sum", [
      { no: 1, name: "data_points", kind: "message", repeat: 2, /*RepeatType.UNPACKED*/ T: () => NumberDataPoint },
      {
        no: 2,
        name: "aggregation_temporality",
        kind: "enum",
        T: () => [
          "opentelemetry.proto.metrics.v1.AggregationTemporality",
          AggregationTemporality,
          "AGGREGATION_TEMPORALITY_",
        ],
      },
      { no: 3, name: "is_monotonic", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
    ]);
  }
  override create(value?: PartialMessage<Sum>): Sum {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.dataPoints = [];
    message.aggregationTemporality = 0;
    message.isMonotonic = false;
    if (value !== undefined) {
      reflectionMergePartial<Sum>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Sum): Sum {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* repeated opentelemetry.proto.metrics.v1.NumberDataPoint data_points */ 1:
          message.dataPoints.push(NumberDataPoint.internalBinaryRead(reader, reader.uint32(), options));
          break;
        case /* opentelemetry.proto.metrics.v1.AggregationTemporality aggregation_temporality */ 2:
          message.aggregationTemporality = reader.int32();
          break;
        case /* bool is_monotonic */ 3:
          message.isMonotonic = reader.bool();
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(message: Sum, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
    /* repeated opentelemetry.proto.metrics.v1.NumberDataPoint data_points = 1; */
    for (let i = 0; i < message.dataPoints.length; i++) {
      NumberDataPoint.internalBinaryWrite(
        message.dataPoints[i],
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    }
    /* opentelemetry.proto.metrics.v1.AggregationTemporality aggregation_temporality = 2; */
    if (message.aggregationTemporality !== 0) {
      writer.tag(2, WireType.Varint).int32(message.aggregationTemporality);
    }
    /* bool is_monotonic = 3; */
    if (message.isMonotonic !== false) {
      writer.tag(3, WireType.Varint).bool(message.isMonotonic);
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.metrics.v1.Sum
 */
export const Sum = new Sum$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Histogram$Type extends MessageType<Histogram> {
  constructor() {
    super("opentelemetry.proto.metrics.v1.Histogram", [
      { no: 1, name: "data_points", kind: "message", repeat: 2, /*RepeatType.UNPACKED*/ T: () => HistogramDataPoint },
      {
        no: 2,
        name: "aggregation_temporality",
        kind: "enum",
        T: () => [
          "opentelemetry.proto.metrics.v1.AggregationTemporality",
          AggregationTemporality,
          "AGGREGATION_TEMPORALITY_",
        ],
      },
    ]);
  }
  override create(value?: PartialMessage<Histogram>): Histogram {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.dataPoints = [];
    message.aggregationTemporality = 0;
    if (value !== undefined) {
      reflectionMergePartial<Histogram>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: Histogram,
  ): Histogram {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* repeated opentelemetry.proto.metrics.v1.HistogramDataPoint data_points */ 1:
          message.dataPoints.push(HistogramDataPoint.internalBinaryRead(reader, reader.uint32(), options));
          break;
        case /* opentelemetry.proto.metrics.v1.AggregationTemporality aggregation_temporality */ 2:
          message.aggregationTemporality = reader.int32();
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(message: Histogram, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
    /* repeated opentelemetry.proto.metrics.v1.HistogramDataPoint data_points = 1; */
    for (let i = 0; i < message.dataPoints.length; i++) {
      HistogramDataPoint.internalBinaryWrite(
        message.dataPoints[i],
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    }
    /* opentelemetry.proto.metrics.v1.AggregationTemporality aggregation_temporality = 2; */
    if (message.aggregationTemporality !== 0) {
      writer.tag(2, WireType.Varint).int32(message.aggregationTemporality);
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.metrics.v1.Histogram
 */
export const Histogram = new Histogram$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Summary$Type extends MessageType<Summary> {
  constructor() {
    super("opentelemetry.proto.metrics.v1.Summary", [
      { no: 1, name: "data_points", kind: "message", repeat: 2, /*RepeatType.UNPACKED*/ T: () => SummaryDataPoint },
    ]);
  }
  override create(value?: PartialMessage<Summary>): Summary {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.dataPoints = [];
    if (value !== undefined) {
      reflectionMergePartial<Summary>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: Summary,
  ): Summary {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* repeated opentelemetry.proto.metrics.v1.SummaryDataPoint data_points */ 1:
          message.dataPoints.push(SummaryDataPoint.internalBinaryRead(reader, reader.uint32(), options));
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(message: Summary, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
    /* repeated opentelemetry.proto.metrics.v1.SummaryDataPoint data_points = 1; */
    for (let i = 0; i < message.dataPoints.length; i++) {
      SummaryDataPoint.internalBinaryWrite(
        message.dataPoints[i],
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.metrics.v1.Summary
 */
export const Summary = new Summary$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NumberDataPoint$Type extends MessageType<NumberDataPoint> {
  constructor() {
    super("opentelemetry.proto.metrics.v1.NumberDataPoint", [
      { no: 7, name: "attributes", kind: "message", repeat: 2, /*RepeatType.UNPACKED*/ T: () => KeyValue },
      { no: 2, name: "start_time_unix_nano", kind: "scalar", T: 6, /*ScalarType.FIXED64*/ L: 0 /*LongType.BIGINT*/ },
      { no: 3, name: "time_unix_nano", kind: "scalar", T: 6, /*ScalarType.FIXED64*/ L: 0 /*LongType.BIGINT*/ },
      { no: 4, name: "as_double", kind: "scalar", oneof: "value", T: 1 /*ScalarType.DOUBLE*/ },
      {
        no: 6,
        name: "as_int",
        kind: "scalar",
        oneof: "value",
        T: 16, /*ScalarType.SFIXED64*/
        L: 0, /*LongType.BIGINT*/
      },
    ]);
  }
  override create(value?: PartialMessage<NumberDataPoint>): NumberDataPoint {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.attributes = [];
    message.startTimeUnixNano = 0n;
    message.timeUnixNano = 0n;
    message.value = { oneofKind: undefined };
    if (value !== undefined) {
      reflectionMergePartial<NumberDataPoint>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: NumberDataPoint,
  ): NumberDataPoint {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* repeated opentelemetry.proto.common.v1.KeyValue attributes */ 7:
          message.attributes.push(KeyValue.internalBinaryRead(reader, reader.uint32(), options));
          break;
        case /* fixed64 start_time_unix_nano */ 2:
          message.startTimeUnixNano = reader.fixed64().toBigInt();
          break;
        case /* fixed64 time_unix_nano */ 3:
          message.timeUnixNano = reader.fixed64().toBigInt();
          break;
        case /* double as_double */ 4:
          message.value = {
            oneofKind: "asDouble",
            asDouble: reader.double(),
          };
          break;
        case /* sfixed64 as_int */ 6:
          message.value = {
            oneofKind: "asInt",
            asInt: reader.sfixed64().toBigInt(),
          };
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(
    message: NumberDataPoint,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* fixed64 start_time_unix_nano = 2; */
    if (message.startTimeUnixNano !== 0n) {
      writer.tag(2, WireType.Bit64).fixed64(message.startTimeUnixNano);
    }
    /* fixed64 time_unix_nano = 3; */
    if (message.timeUnixNano !== 0n) {
      writer.tag(3, WireType.Bit64).fixed64(message.timeUnixNano);
    }
    /* double as_double = 4; */
    if (message.value.oneofKind === "asDouble") {
      writer.tag(4, WireType.Bit64).double(message.value.asDouble);
    }
    /* sfixed64 as_int = 6; */
    if (message.value.oneofKind === "asInt") {
      writer.tag(6, WireType.Bit64).sfixed64(message.value.asInt);
    }
    /* repeated opentelemetry.proto.common.v1.KeyValue attributes = 7; */
    for (let i = 0; i < message.attributes.length; i++) {
      KeyValue.internalBinaryWrite(message.attributes[i], writer.tag(7, WireType.LengthDelimited).fork(), options)
        .join();
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.metrics.v1.NumberDataPoint
 */
export const NumberDataPoint = new NumberDataPoint$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HistogramDataPoint$Type extends MessageType<HistogramDataPoint> {
  constructor() {
    super("opentelemetry.proto.metrics.v1.HistogramDataPoint", [
      { no: 9, name: "attributes", kind: "message", repeat: 2, /*RepeatType.UNPACKED*/ T: () => KeyValue },
      { no: 2, name: "start_time_unix_nano", kind: "scalar", T: 6, /*ScalarType.FIXED64*/ L: 0 /*LongType.BIGINT*/ },
      { no: 3, name: "time_unix_nano", kind: "scalar", T: 6, /*ScalarType.FIXED64*/ L: 0 /*LongType.BIGINT*/ },
      { no: 4, name: "count", kind: "scalar", T: 4, /*ScalarType.UINT64*/ L: 0 /*LongType.BIGINT*/ },
      { no: 5, name: "sum", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
      {
        no: 6,
        name: "bucket_counts",
        kind: "scalar",
        repeat: 1, /*RepeatType.PACKED*/
        T: 4, /*ScalarType.UINT64*/
        L: 0, /*LongType.BIGINT*/
      },
      { no: 7, name: "explicit_bounds", kind: "scalar", repeat: 1, /*RepeatType.PACKED*/ T: 1 /*ScalarType.DOUBLE*/ },
    ]);
  }
  override create(value?: PartialMessage<HistogramDataPoint>): HistogramDataPoint {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.attributes = [];
    message.startTimeUnixNano = 0n;
    message.timeUnixNano = 0n;
    message.count = 0n;
    message.sum = 0;
    message.bucketCounts = [];
    message.explicitBounds = [];
    if (value !== undefined) {
      reflectionMergePartial<HistogramDataPoint>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: HistogramDataPoint,
  ): HistogramDataPoint {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* repeated opentelemetry.proto.common.v1.KeyValue attributes */ 9:
          message.attributes.push(KeyValue.internalBinaryRead(reader, reader.uint32(), options));
          break;
        case /* fixed64 start_time_unix_nano */ 2:
          message.startTimeUnixNano = reader.fixed64().toBigInt();
          break;
        case /* fixed64 time_unix_nano */ 3:
          message.timeUnixNano = reader.fixed64().toBigInt();
          break;
        case /* uint64 count */ 4:
          message.count = reader.uint64().toBigInt();
          break;
        case /* double sum */ 5:
          message.sum = reader.double();
          break;
        case /* repeated uint64 bucket_counts */ 6:
          if (wireType === WireType.LengthDelimited) {
            for (let e = reader.int32() + reader.pos; reader.pos < e;) {
              message.bucketCounts.push(reader.uint64().toBigInt());
            }
          } else {
            message.bucketCounts.push(reader.uint64().toBigInt());
          }
          break;
        case /* repeated double explicit_bounds */ 7:
          if (wireType === WireType.LengthDelimited) {
            for (let e = reader.int32() + reader.pos; reader.pos < e;) {
              message.explicitBounds.push(reader.double());
            }
          } else {
            message.explicitBounds.push(reader.double());
          }
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(
    message: HistogramDataPoint,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* fixed64 start_time_unix_nano = 2; */
    if (message.startTimeUnixNano !== 0n) {
      writer.tag(2, WireType.Bit64).fixed64(message.startTimeUnixNano);
    }
    /* fixed64 time_unix_nano = 3; */
    if (message.timeUnixNano !== 0n) {
      writer.tag(3, WireType.Bit64).fixed64(message.timeUnixNano);
    }
    /* uint64 count = 4; */
    if (message.count !== 0n) {
      writer.tag(4, WireType.Varint).uint64(message.count);
    }
    /* double sum = 5; */
    if (message.sum !== 0) {
      writer.tag(5, WireType.Bit64).double(message.sum);
    }
    /* repeated uint64 bucket_counts = 6; */
    if (message.bucketCounts.length) {
      writer.tag(6, WireType.LengthDelimited).fork();
      for (let i = 0; i < message.bucketCounts.length; i++) {
        writer.uint64(message.bucketCounts[i]);
      }
      writer.join();
    }
    /* repeated double explicit_bounds = 7; */
    if (message.explicitBounds.length) {
      writer.tag(7, WireType.LengthDelimited).fork();
      for (let i = 0; i < message.explicitBounds.length; i++) {
        writer.double(message.explicitBounds[i]);
      }
      writer.join();
    }
    /* repeated opentelemetry.proto.common.v1.KeyValue attributes = 9; */
    for (let i = 0; i < message.attributes.length; i++) {
      KeyValue.internalBinaryWrite(message.attributes[i], writer.tag(9, WireType.LengthDelimited).fork(), options)
        .join();
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.metrics.v1.HistogramDataPoint
 */
export const HistogramDataPoint = new HistogramDataPoint$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SummaryDataPoint$Type extends MessageType<SummaryDataPoint> {
  constructor() {
    super("opentelemetry.proto.metrics.v1.SummaryDataPoint", [
      { no: 7, name: "attributes", kind: "message", repeat: 2, /*RepeatType.UNPACKED*/ T: () => KeyValue },
      { no: 2, name: "start_time_unix_nano", kind: "scalar", T: 6, /*ScalarType.FIXED64*/ L: 0 /*LongType.BIGINT*/ },
      { no: 3, name: "time_unix_nano", kind: "scalar", T: 6, /*ScalarType.FIXED64*/ L: 0 /*LongType.BIGINT*/ },
      { no: 4, name: "count", kind: "scalar", T: 4, /*ScalarType.UINT64*/ L: 0 /*LongType.BIGINT*/ },
      { no: 5, name: "sum", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
      { no: 6, name: "quantile_values", kind: "message", repeat: 2, /*RepeatType.UNPACKED*/ T: () => ValueAtQuantile },
    ]);
  }
  override create(value?: PartialMessage<SummaryDataPoint>): SummaryDataPoint {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.attributes = [];
    message.startTimeUnixNano = 0n;
    message.timeUnixNano = 0n;
    message.count = 0n;
    message.sum = 0;
    message.quantileValues = [];
    if (value !== undefined) {
      reflectionMergePartial<SummaryDataPoint>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: SummaryDataPoint,
  ): SummaryDataPoint {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* repeated opentelemetry.proto.common.v1.KeyValue attributes */ 7:
          message.attributes.push(KeyValue.internalBinaryRead(reader, reader.uint32(), options));
          break;
        case /* fixed64 start_time_unix_nano */ 2:
          message.startTimeUnixNano = reader.fixed64().toBigInt();
          break;
        case /* fixed64 time_unix_nano */ 3:
          message.timeUnixNano = reader.fixed64().toBigInt();
          break;
        case /* uint64 count */ 4:
          message.count = reader.uint64().toBigInt();
          break;
        case /* double sum */ 5:
          message.sum = reader.double();
          break;
        case /* repeated opentelemetry.proto.metrics.v1.ValueAtQuantile quantile_values */ 6:
          message.quantileValues.push(ValueAtQuantile.internalBinaryRead(reader, reader.uint32(), options));
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(
    message: SummaryDataPoint,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* fixed64 start_time_unix_nano = 2; */
    if (message.startTimeUnixNano !== 0n) {
      writer.tag(2, WireType.Bit64).fixed64(message.startTimeUnixNano);
    }
    /* fixed64 time_unix_nano = 3; */
    if (message.timeUnixNano !== 0n) {
      writer.tag(3, WireType.Bit64).fixed64(message.timeUnixNano);
    }
    /* uint64 count = 4; */
    if (message.count !== 0n) {
      writer.tag(4, WireType.Varint).uint64(message.count);
    }
    /* double sum = 5; */
    if (message.sum !== 0) {
      writer.tag(5, WireType.Bit64).double(message.sum);
    }
    /* repeated opentelemetry.proto.metrics.v1.ValueAtQuantile quantile_values = 6; */
    for (let i = 0; i < message.quantileValues.length; i++) {
      ValueAtQuantile.internalBinaryWrite(
        message.quantileValues[i],
        writer.tag(6, WireType.LengthDelimited).fork(),
        options,
      ).join();
    }
    /* repeated opentelemetry.proto.common.v1.KeyValue attributes = 7; */
    for (let i = 0; i < message.attributes.length; i++) {
      KeyValue.internalBinaryWrite(message.attributes[i], writer.tag(7, WireType.LengthDelimited).fork(), options)
        .join();
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.metrics.v1.SummaryDataPoint
 */
export const SummaryDataPoint = new SummaryDataPoint$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ValueAtQuantile$Type extends MessageType<ValueAtQuantile> {
  constructor() {
    super("opentelemetry.proto.metrics.v1.ValueAtQuantile", [
      { no: 1, name: "quantile", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
      { no: 2, name: "value", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
    ]);
  }
  override create(value?: PartialMessage<ValueAtQuantile>): ValueAtQuantile {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.quantile = 0;
    message.value = 0;
    if (value !== undefined) {
      reflectionMergePartial<ValueAtQuantile>(this, message, value);
    }
    return message;
  }
  override internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: ValueAtQuantile,
  ): ValueAtQuantile {
    let message = target ?? this.create(), end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* double quantile */ 1:
          message.quantile = reader.double();
          break;
        case /* double value */ 2:
          message.value = reader.double();
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw") {
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          }
          let d = reader.skip(wireType);
          if (u !== false) {
            (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
          }
      }
    }
    return message;
  }
  override internalBinaryWrite(
    message: ValueAtQuantile,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* double quantile = 1; */
    if (message.quantile !== 0) {
      writer.tag(1, WireType.Bit64).double(message.quantile);
    }
    /* double value = 2; */
    if (message.value !== 0) {
      writer.tag(2, WireType.Bit64).double(message.value);
    }
    let u = options.writeUnknownFields;
    if (u !== false) {
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    }
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message opentelemetry.proto.metrics.v1.ValueAtQuantile
 */
export const ValueAtQuantile = new ValueAtQuantile$Type();
